import {Metadata} from "next";
import {Fragment} from "react";

export default function Page () {
  return (
    <Fragment>
      <p>contact us</p>
    </Fragment>
  )
}

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};
