import {Fragment} from "react";
import {Metadata} from "next";
import Hero from "@/components/Hero/Hero";
import Ribbon from "@/components/Ribbon/Ribbon";
import TwoColumn from "@/components/TwoColumn/TwoColumn";
import BulletinBoard from "@/components/BulletinBoard/BulletinBoard";
import Newsletter from "@/components/Newsletter/Newsletter";

export default function Home() {
  return (
    <Fragment>
      <Hero/>
      <Ribbon
        theme="light"
        sentences={["INCLUDES NEW FRIENDS AND MORE SMILES", "THE WORLD’S FASTEST GROWING SPORT IS COMING TO LONG ISLAND", "IT´S NOT A SPORT, IT´S AN ADDICTION"]}
      />
      <TwoColumn
        image="/images/shutterstock_1990151645.jpg"
        imagePosition="left"
        headline="Interested in a career with us? Join our team today!"
        paragraph="Join our dynamic team at Padel&! We’re hiring a Club Manager, Receptionist, and Personal Trainer. If you’re passionate, energetic, and ready for a new challenge, apply now and be a part of our club!"
        buttonLink="/join-our-team"
      />
      <TwoColumn
        image="/images/shutterstock_2484387677.jpg"
        imagePosition="right"
        headline="Grand Opening at Padel& Syosset!"
        paragraph="We’re thrilled to open at 165 Eileen Way, Syosset, Long Island! With 4 courts, a pro-shop, locker rooms, and a fantastic team, it’s the perfect spot for padel enthusiasts. Can’t wait to see you this fall!"
      />
      <BulletinBoard
        headline="&quot;We're proud to elevate padel in New York!&quot;"
        subHeadline="- The Hellkvist Brothers"
        leftImage="/images/shutterstock_2237057977.jpg"
        rightImage="/images/shutterstock_2472341961.jpg"
      />
      <Ribbon
        sentences={["INCLUDES NEW FRIENDS AND MORE SMILES", "THE WORLD’S FASTEST GROWING SPORT IS COMING TO LONG ISLAND", "IT´S NOT A SPORT, IT´S AN ADDICTION"]}
        theme="dark"
      />
      <Newsletter/>
    </Fragment>
  );
}

export const metadata: Metadata = {
  title: "Padel&",
  description: "Generated by create next app",
};
