import {Fragment} from "react";
import {Metadata} from "next";
import Hero from "@/components/Hero/Hero";
import Ribbon from "@/components/Ribbon/Ribbon";

export default function Home() {
  return (
    <Fragment>
      <Hero/>
      <Ribbon/>
    </Fragment>
  );
}

export const metadata: Metadata = {
  title: "Padel&",
  description: "Generated by create next app",
};
